# Generated by Django 5.0.6 on 2024-07-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=10, null=True),
        ),
    ]
