# Generated by Django 5.0.6 on 2024-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/'),
        ),
    ]
